services:
  - type: web
    name: book-loop-backend
    env: node
    region: oregon       # or your preferred region
    branch: main         # the Git branch to auto-deploy
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: MONGODB_URI
        fromSecret: mongodb_uri
      - key: JWT_SECRET
        fromSecret: jwt_secret